/* eslint-disable react/no-unknown-property */
/* eslint-disable no-unused-vars */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.0.9 blue-butterfly.gltf --transform
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export function BlueButterfly(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/blue-butterfly-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.48, 0.1, 0.53]}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone001} />
        </group>
        <mesh
          name="Cylinder009"
          geometry={nodes.Cylinder009.geometry}
          material={materials["Material.007"]}
          position={[-0.44, 0.16, -0.31]}
          rotation={[1.75, 0, 0]}
          scale={[-0.26, -0.2, -0.2]}
        />
        <mesh
          name="Cylinder001"
          geometry={nodes.Cylinder001.geometry}
          material={materials["Material.006"]}
          position={[-0.44, -0.01, -0.07]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.02}
        />
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials["Material.001"]}
          position={[-0.53, 0.02, 0.08]}
          scale={0.11}
        />
        <mesh
          name="Cube002"
          geometry={nodes.Cube002.geometry}
          material={materials["Material.007"]}
          position={[0.09, -0.21, 0.86]}
          scale={[0.23, 0.16, 0.16]}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials["Material.003"]}
          position={[-0.46, 0.01, 1.27]}
          rotation={[1.64, 0, -Math.PI]}
          scale={[0.07, 0.54, 0.08]}
        />
        <mesh
          name="Cube001"
          geometry={nodes.Cube001.geometry}
          material={materials["Material.006"]}
          position={[-0.45, 0.02, 0.53]}
          scale={[0.21, 0.21, 0.26]}
        />
        <mesh
          name="Cube"
          geometry={nodes.Cube.geometry}
          material={materials.Material}
          position={[-0.46, 0.03, 1.03]}
          scale={0.21}
        />
        <skinnedMesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
          skeleton={nodes.Plane.skeleton}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/blue-butterfly-transformed.glb");
